on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to HuggingFace Space
        run: git push https://ipriyanshyadav:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ipriyanshyadav/Combined-Rag-Tool-Chatbot-Blog-Writing-agent- main
